#!/bin/bash

piScope_REPO=piScope

STRUMPACK_REPO=STRUMPACK-3.1.1
GMSH=gmsh-4.5.6
OCC=opencascade-7.4.0
PyOCC=pythonocc-core
HYPRE_VERSION=2.18.2
MUMPS_VERSION=5.3.3
MUMPS_REPO=MUMPS_${MUMPS_VERSION}
LAPACK_VERSION=3.9.0

CXX11FLAG=-std=c++11

